z = "mpc toggle -q"
t = "urxvt"

s = "autoly save"
l = "autoly load"
q = "autoly close"

# enter = "urxvt"

x = "mpc next -q"
c = "nextalbum"

1 = "autoly focus1"
2 = "autoly focus2"
3 = "autoly focus3"
4 = "autoly focus4"
5 = "autoly focus5"
6 = "autoly focus6"
7 = "autoly focus7"
8 = "autoly focus8"
9 = "autoly focus9"
0 = "autoly focus10"
